version: '2'

networks:
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1

services:
  cassandra:
    image: cassandra:3.11.6
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
    ulimits:
      memlock: -1
    networks:
      back:
        ipv4_address: 172.20.10.11

  spring_boot:
    depends_on:
      - cassandra
    build: .
    image: spring-boot-hotel-reservation:latest
    ports:
      - "8080:8080"
    environment:
      CASSANDRA_CONTACT_HOST: 172.20.10.11
      CASSANDRA_CONTACT_PORT: 9042
    networks:
      back:
        ipv4_address: 172.20.10.101

    # If you want to save data directories across runs
    # volumes:
    #   - ~/cassandra/:/var/lib/cassandra/data
 
# If you want to have cqksh
#  docker exec -it `docker ps | grep cassandra:3.11.4 | cut -b 1-12` cqlsh
    
  