# ----------------------------------------------------------
# Spring Boot Config
# ----------------------------------------------------------
spring:
  application:
    name: Reservation Reservicess
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8080

# ----------------------------------------------------------
# DataStax Enterprise Java Driver Config
# ----------------------------------------------------------
cassandra:
  keyspaceName: reservation
